import { useCallback, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { router, useFocusEffect } from "expo-router";

import { AppScreen } from "@/components/AppScreen";
import { Card } from "@/components/Card";
import { EmptyStateCard } from "@/components/EmptyStateCard";
import { PageHeader } from "@/components/PageHeader";
import { PrimaryButton } from "@/components/PrimaryButton";
import { SectionTitle } from "@/components/SectionTitle";
import { colors } from "@/constants/theme";
import { getSavedPlaces } from "@/storage/placeStorage";
import {
  addFieldSeedInboxItem,
  deleteFieldSeedInboxItem,
  FieldSeedInboxItem,
  getFieldSeedInboxItems,
} from "@/storage/fieldSeedInboxStorage";
import {
  acceptFieldSeedInboxItem,
  rejectFieldSeedInboxItem,
} from "@/utils/fieldSeedInboxActions";
import {
  getTaskContextLabel,
  getTaskPriorityLabel,
} from "@/utils/taskMetadata";
import { getReminderProfileLabel } from "@/utils/reminderProfiles";

function formatDate(value?: string) {
  if (!value) {
    return "Not reviewed";
  }

  return new Date(value).toLocaleString();
}

type InboxCardProps = {
  item: FieldSeedInboxItem;
  onAccept: () => void;
  onReject: () => void;
  onDelete: () => void;
};

function InboxCard({ item, onAccept, onReject, onDelete }: InboxCardProps) {
  const isPending = item.status === "pending";

  return (
    <Card>
      <View style={styles.cardHeader}>
        <Text style={styles.taskTitle}>{item.title}</Text>
        <Text style={[styles.statusBadge, !isPending && styles.statusBadgeMuted]}>
          {item.status}
        </Text>
      </View>

      <Text style={styles.taskMeta}>Place: {item.placeName}</Text>
      <Text style={styles.taskMeta}>Due: {item.dueDate}{item.dueTime ? ` • ${item.dueTime}` : ""}</Text>
      <Text style={styles.taskMeta}>Priority: {getTaskPriorityLabel(item.priority)}</Text>
      <Text style={styles.taskMeta}>Context: {getTaskContextLabel(item.contextType)}</Text>
      <Text style={styles.taskMeta}>Reminder: {getReminderProfileLabel(item.reminderProfile)}</Text>

      {item.notes && <Text style={styles.notes}>{item.notes}</Text>}

      {!isPending && (
        <Text style={styles.reviewText}>Reviewed: {formatDate(item.reviewedAt)}</Text>
      )}

      {isPending ? (
        <View style={styles.actionRow}>
          <View style={styles.actionButton}>
            <PrimaryButton title="Accept" onPress={onAccept} />
          </View>

          <View style={styles.actionButton}>
            <PrimaryButton title="Reject" variant="secondary" onPress={onReject} />
          </View>
        </View>
      ) : (
        <Pressable style={styles.deleteLink} onPress={onDelete}>
          <Text style={styles.deleteText}>Delete from inbox</Text>
        </Pressable>
      )}
    </Card>
  );
}

export default function FieldSeedInboxScreen() {
  const [items, setItems] = useState<FieldSeedInboxItem[]>([]);
  const [statusMessage, setStatusMessage] = useState(
    "Review work tasks generated by FieldSeed before adding them to GPS Context Assistant."
  );

  async function loadInbox() {
    const savedItems = await getFieldSeedInboxItems();
    setItems(savedItems);
  }

  useFocusEffect(
    useCallback(() => {
      loadInbox();
    }, [])
  );

  const pendingItems = items.filter((item) => item.status === "pending");
  const reviewedItems = items.filter((item) => item.status !== "pending");

  async function handleAccept(item: FieldSeedInboxItem) {
    const result = await acceptFieldSeedInboxItem(item);

    if (!result.accepted) {
      setStatusMessage(result.reason ?? "Could not accept FieldSeed task.");
      Alert.alert(
        "Place not found",
        "Create or rename a place to match this FieldSeed task before accepting it."
      );
      return;
    }

    setStatusMessage("FieldSeed task accepted and added to your task list.");
    setItems(result.inboxItems ?? []);
  }

  async function handleReject(item: FieldSeedInboxItem) {
    const result = await rejectFieldSeedInboxItem(item);
    setStatusMessage("FieldSeed task rejected.");
    setItems(result.inboxItems);
  }

  async function handleDelete(item: FieldSeedInboxItem) {
    const updatedItems = await deleteFieldSeedInboxItem(item.id);
    setStatusMessage("Inbox item deleted.");
    setItems(updatedItems);
  }

  async function handleAddSampleTask() {
    const places = await getSavedPlaces();
    const firstVisiblePlace = places.find((place) => !place.archivedAt);

    if (!firstVisiblePlace) {
      Alert.alert(
        "No place available",
        "Create a place first, then add a sample FieldSeed task."
      );
      return;
    }

    const result = await addFieldSeedInboxItem({
      externalSourceId: `fieldseed-demo-${Date.now()}`,
      title: "Verify site system health",
      notes:
        "Generated by FieldSeed. Review cameras, server health, storage, and unresolved technician notes for this location.",
      placeName: firstVisiblePlace.name,
      priority: "high",
      contextType: firstVisiblePlace.name.toLowerCase().includes("work")
        ? "work"
        : "site",
      reminderProfile: "persistent",
      dueDate: "Next arrival",
    });

    setStatusMessage("Sample FieldSeed task added to inbox.");
    setItems(result.items);
  }

  return (
    <AppScreen>
      <PageHeader
        label="FIELDSEED INBOX"
        title="Review generated work tasks."
        subtitle="FieldSeed can prepare technician tasks, then GPS Context Assistant reminds you when you reach the right place."
      />

      <Card variant="blue">
        <Text style={styles.summaryTitle}>Inbox status</Text>
        <Text style={styles.summaryText}>{statusMessage}</Text>

        <View style={styles.buttonWrapper}>
          <PrimaryButton
            title="Add Sample FieldSeed Task"
            variant="secondary"
            onPress={handleAddSampleTask}
          />
        </View>
      </Card>

      <View style={styles.section}>
        <SectionTitle>Pending Review</SectionTitle>

        {pendingItems.length === 0 ? (
          <EmptyStateCard
            title="No FieldSeed tasks waiting"
            message="Generated work tasks will appear here before they become location-based reminders."
          />
        ) : (
          pendingItems.map((item) => (
            <InboxCard
              key={item.id}
              item={item}
              onAccept={() => handleAccept(item)}
              onReject={() => handleReject(item)}
              onDelete={() => handleDelete(item)}
            />
          ))
        )}
      </View>

      <View style={styles.section}>
        <SectionTitle>Reviewed</SectionTitle>

        {reviewedItems.length === 0 ? (
          <EmptyStateCard
            title="No reviewed tasks yet"
            message="Accepted and rejected FieldSeed tasks will appear here for reference."
          />
        ) : (
          reviewedItems.map((item) => (
            <InboxCard
              key={item.id}
              item={item}
              onAccept={() => handleAccept(item)}
              onReject={() => handleReject(item)}
              onDelete={() => handleDelete(item)}
            />
          ))
        )}
      </View>

      <View style={styles.actions}>
        <PrimaryButton
          title="Back"
          variant="secondary"
          onPress={() => router.back()}
        />
      </View>
    </AppScreen>
  );
}

const styles = StyleSheet.create({
  section: {
    marginBottom: 24,
  },

  summaryTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 6,
  },

  summaryText: {
    color: colors.softText,
    fontSize: 14,
    lineHeight: 20,
  },

  buttonWrapper: {
    marginTop: 14,
  },

  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },

  taskTitle: {
    flex: 1,
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
  },

  statusBadge: {
    color: colors.primary,
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: "900",
  },

  statusBadgeMuted: {
    color: colors.softText,
    backgroundColor: "#F1F5F9",
  },

  taskMeta: {
    color: colors.softText,
    fontSize: 14,
    lineHeight: 22,
  },

  notes: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 10,
  },

  reviewText: {
    color: "#94A3B8",
    fontSize: 12,
    marginTop: 10,
  },

  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },

  actionButton: {
    flex: 1,
  },

  deleteLink: {
    marginTop: 14,
  },

  deleteText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "900",
  },

  actions: {
    gap: 14,
    paddingBottom: 90,
  },
});
