import {
  LocationTask,
  TaskContextType,
  TaskPriority,
  TaskSource,
} from "@/types/task";

export const taskSources: TaskSource[] = ["manual", "fieldseed", "routine"];

export const taskPriorities: TaskPriority[] = [
  "low",
  "normal",
  "high",
  "urgent",
];

export const taskContextTypes: TaskContextType[] = [
  "personal",
  "home",
  "work",
  "errand",
  "site",
];

export function getTaskSourceLabel(source: TaskSource = "manual") {
  if (source === "fieldseed") {
    return "FieldSeed";
  }

  if (source === "routine") {
    return "Routine";
  }

  return "Manual";
}

export function getTaskSourceDescription(source: TaskSource = "manual") {
  if (source === "fieldseed") {
    return "Generated by FieldSeed or imported from technician workflows.";
  }

  if (source === "routine") {
    return "A repeated habit, checklist, or recurring task.";
  }

  return "Created directly in GPS Context Assistant.";
}

export function getTaskPriorityLabel(priority: TaskPriority = "normal") {
  if (priority === "urgent") return "Urgent";
  if (priority === "high") return "High";
  if (priority === "low") return "Low";
  return "Normal";
}

export function getTaskPriorityDescription(priority: TaskPriority = "normal") {
  if (priority === "urgent") {
    return "Critical task. Should be surfaced before everything else.";
  }

  if (priority === "high") {
    return "Important task. Should appear near the top.";
  }

  if (priority === "low") {
    return "Useful but not time-sensitive.";
  }

  return "Standard task priority.";
}

export function getTaskContextLabel(contextType: TaskContextType = "personal") {
  if (contextType === "home") return "Home";
  if (contextType === "work") return "Work";
  if (contextType === "errand") return "Errand";
  if (contextType === "site") return "Site";
  return "Personal";
}

export function getTaskContextDescription(
  contextType: TaskContextType = "personal"
) {
  if (contextType === "home") {
    return "Connected to home life, family, or household reminders.";
  }

  if (contextType === "work") {
    return "Connected to office work, job tasks, or technician prep.";
  }

  if (contextType === "errand") {
    return "Connected to stores, appointments, or stops while out.";
  }

  if (contextType === "site") {
    return "Connected to a customer site, field visit, or service location.";
  }

  return "General life task.";
}

export function getTaskPriorityWeight(priority?: TaskPriority) {
  if (priority === "urgent") return 4;
  if (priority === "high") return 3;
  if (priority === "low") return 1;
  return 2;
}

export function sortTasksByPriority(tasks: LocationTask[]) {
  return [...tasks].sort((firstTask, secondTask) => {
    const priorityDifference =
      getTaskPriorityWeight(secondTask.priority) -
      getTaskPriorityWeight(firstTask.priority);

    if (priorityDifference !== 0) {
      return priorityDifference;
    }

    return firstTask.title.localeCompare(secondTask.title);
  });
}
